using System;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;

/// <summary>
/// Summary description for Reporter
/// </summary>
public class Reporter
{
	public Reporter()
	{
		//
		// TODO: Add constructor logic here
		//
	}
    public static DataTable  GetTable(DataTable dt , string ColStr)
    {
        foreach (DataColumn dc in dt.Columns)
        {
            Boolean flag = false;

            foreach (string Col in ColStr.Split (','))
            {
                if (dc.ColumnName.ToString().ToUpper() == Col.ToUpper())
                {
                    flag = true;
                    dt.Columns.Remove(dc);
                    break;
                }
            }
        
        }


        //DataTable Newdt = new DataTable();

        //foreach (string Col in ColStr.Split (','))
        //{
        //    DataColumn dc = new DataColumn ();
        //    dc.ColumnName = Col;
        //    dc.DataType = dt.Columns[Col].GetType();
        //    Newdt.Columns.Add(dc);
        //}
        //foreach (DataRow dr in dt.Rows)
        //{
        //    DataRow newdr = Newdt.NewRow();
        //    foreach (string Col in ColStr.Split(','))
        //    {
        //        newdr[Col] = dr[Col];
           
        //    }
        //    Newdt.Rows.Add(newdr);
        //}

        return dt;    
    }

    public string RawQueryForAll(Boolean WHBasedFILO)
    {
       // LoadSelections();
        string ODstr = " (SELECT ISNULL(SUM(WORKEDMINUTES),0) FROM TK_ONDUTY WHERE ATTENDANCEID = AT.ATTENDANCEID AND INCLUDEINWORKINGHOURS = 1) ";
        string PerStr = " (SELECT ISNULL(SUM(DURATIONMINUTES),0) FROM TK_TIMEPERMISSION WHERE ATTENDANCEID = AT.ATTENDANCEID  AND INCLUDEINWORKINGHOURS = 1 ) ";

        string SubQueryStr = " SELECT EM.EMPLOYEECODE,EM.EMPLOYEEID, EM.EMPLOYEEFIRSTNAME + '' + EM.EMPLOYEELASTNAME AS EMPLOYEENAME, AT.STATUS,CASE WHEN EM.GENDER=1 THEN 'MALE' ELSE 'FEMALE' END AS GENDER ,  SH.SHIFTID,PSH.SHIFTID AS PRESENTSHIFTID ,PSH.BEGINTIME,PSH.ENDTIME,PSH.SHIFTDURATION,( PSH.SHIFTDURATION * 60) +     (PSH.SHIFTDURATION - FLOOR(PSH.SHIFTDURATION)) AS SHIFTDURATIONMINUTES,EM.SECTIONID, " +
           "\n" + "SH.ISSAMEDAY,AT.ATTENDANCEDATE, ISONLEAVE, ISONTOUR, LATECOMINGGRACETIME, EARLYGOINGGRACETIME, ";
        if (SamayBioLib.GlobalObjects.ObjCompany.WHBasedFILO)
        {
            SubQueryStr += "\n" + "CONVERT(VARCHAR, FLOOR((ABS(ISNULL(DATEDIFF(MI,ISNULL(OUTTIME8,ISNULL(INTIME8,ISNULL(OUTTIME7,ISNULL(INTIME7,ISNULL(OUTTIME6,ISNULL(INTIME6,ISNULL(OUTTIME5, " +
                    " ISNULL(INTIME5,ISNULL(OUTTIME4,ISNULL(INTIME4,ISNULL(OUTTIME3,ISNULL(INTIME3,ISNULL(OUTTIME2,ISNULL(INTIME2,ISNULL(OUTTIME2,ISNULL(INTIME2,OUTTIME1)))))))))))))))), " +
                    " INTIME1),0)) + " + ODstr + " + " + PerStr + ")/60.0)) + ':' +RIGHT ('0'+ " +
                    " CONVERT(VARCHAR, FLOOR((ABS(ISNULL(DATEDIFF(MI,ISNULL(OUTTIME8,ISNULL(INTIME8,ISNULL(OUTTIME7,ISNULL(INTIME7,ISNULL(OUTTIME6,ISNULL(INTIME6,ISNULL(OUTTIME5, " +
                    " ISNULL(INTIME5,ISNULL(OUTTIME4,ISNULL(INTIME4,ISNULL(OUTTIME3,ISNULL(INTIME3,ISNULL(OUTTIME2,ISNULL(INTIME2,ISNULL(OUTTIME2,ISNULL(INTIME2,OUTTIME1)))))))))))))))), " +
                    " INTIME1),0)) +" + ODstr + "+" + PerStr + ") %60) ),2)  AS WORKEDHOURS, ";
        }

        else
        {
            //SubQueryStr +=   "\n" + "ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(DATEDIFF(MI,INTIME1,OUTTIME1)/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(DATEDIFF(MI,INTIME1,OUTTIME1)) - ( ABS((DATEDIFF(MI,INTIME1,OUTTIME1))/60)*60)),2))),0)  + " +
            // "\n" + "ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(DATEDIFF(MI,INTIME2,OUTTIME2)/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(DATEDIFF(MI,INTIME2,OUTTIME2)) - ( ABS((DATEDIFF(MI,INTIME2,OUTTIME2))/60)*60)),2))),0)  +  " +
            // "\n" + "ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(DATEDIFF(MI,INTIME3,OUTTIME3)/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(DATEDIFF(MI,INTIME3,OUTTIME3)) - ( ABS((DATEDIFF(MI,INTIME3,OUTTIME3))/60)*60)),2))),0)  +  " +
            // "\n" + "ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(DATEDIFF(MI,INTIME4,OUTTIME4)/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(DATEDIFF(MI,INTIME4,OUTTIME4)) - ( ABS((DATEDIFF(MI,INTIME4,OUTTIME4))/60)*60)),2))),0)  +  " +
            // "\n" + "ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(DATEDIFF(MI,INTIME5,OUTTIME5)/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(DATEDIFF(MI,INTIME5,OUTTIME5)) - ( ABS((DATEDIFF(MI,INTIME5,OUTTIME5))/60)*60)),2))),0)  +  " +
            // "\n" + "ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(DATEDIFF(MI,INTIME6,OUTTIME6)/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(DATEDIFF(MI,INTIME6,OUTTIME6)) - ( ABS((DATEDIFF(MI,INTIME6,OUTTIME6))/60)*60)),2))),0)  +  " +
            // "\n" + "ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(DATEDIFF(MI,INTIME7,OUTTIME7)/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(DATEDIFF(MI,INTIME7,OUTTIME7)) - ( ABS((DATEDIFF(MI,INTIME7,OUTTIME7))/60)*60)),2))),0)  + " +
            // "\n" + "ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(DATEDIFF(MI,INTIME8,OUTTIME8)/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(DATEDIFF(MI,INTIME8,OUTTIME8)) - ( ABS((DATEDIFF(MI,INTIME8,OUTTIME8))/60)*60)),2))),0)  AS WORKEDHOURS,";

            SubQueryStr += " CONVERT(VARCHAR, FLOOR((ABS(ISNULL(DATEDIFF (MI,INTIME1,OUTTIME1),0) +  ISNULL(DATEDIFF (MI,INTIME2,OUTTIME2),0) +  ISNULL(DATEDIFF (MI,INTIME3,OUTTIME3),0) +   " +
                       " ISNULL(DATEDIFF (MI,INTIME4,OUTTIME4),0) +  ISNULL(DATEDIFF (MI,INTIME5,OUTTIME5),0) +  ISNULL(DATEDIFF (MI,INTIME6,OUTTIME6),0) +   " +
                       " ISNULL(DATEDIFF (MI,INTIME7,OUTTIME7),0) +  ISNULL(DATEDIFF (MI,INTIME8,OUTTIME8),0) ) + " + ODstr + "+" + PerStr + ")/60.0)) + ':' + RIGHT ('0'+ CONVERT(VARCHAR,ABS((ISNULL(DATEDIFF (MI,INTIME1,OUTTIME1),0) +  ISNULL(DATEDIFF (MI,INTIME2,OUTTIME2),0) +  ISNULL(DATEDIFF (MI,INTIME3,OUTTIME3),0) +   " +
                       " ISNULL(DATEDIFF (MI,INTIME4,OUTTIME4),0) +  ISNULL(DATEDIFF (MI,INTIME5,OUTTIME5),0) +  ISNULL(DATEDIFF (MI,INTIME6,OUTTIME6),0) +  " +
                       " ISNULL(DATEDIFF (MI,INTIME7,OUTTIME7),0) +  ISNULL(DATEDIFF (MI,INTIME8,OUTTIME8),0) ) + " + ODstr + "+" + PerStr + ") % 60),2) AS WORKEDHOURS, ";


        }

        SubQueryStr += "\n" + "CONVERT(INT,  ISNULL(DATEDIFF (MI,INTIME1,OUTTIME1),0) +  ISNULL(DATEDIFF (MI,INTIME2,OUTTIME2),0) +  ISNULL(DATEDIFF (MI,INTIME3,OUTTIME3),0) +  ISNULL(DATEDIFF (MI,INTIME4,OUTTIME4),0) +  ISNULL(DATEDIFF (MI,INTIME5,OUTTIME5),0) + ISNULL(DATEDIFF (MI,INTIME6,OUTTIME6),0) +  ISNULL(DATEDIFF (MI,INTIME7,OUTTIME7),0) +  ISNULL(DATEDIFF (MI,INTIME8,OUTTIME8),0)  - ( PSH.SHIFTDURATION * 60) +     (PSH.SHIFTDURATION - FLOOR(PSH.SHIFTDURATION))) AS EXTRALESSWORKMINUTES  ," +
           "\n" + "ISNULL(DATEDIFF (MI,INTIME1,OUTTIME1),0) +  ISNULL(DATEDIFF (MI,INTIME2,OUTTIME2),0) +  ISNULL(DATEDIFF (MI,INTIME3,OUTTIME3),0) +  " +
           "\n" + "ISNULL(DATEDIFF (MI,INTIME4,OUTTIME4),0) +  ISNULL(DATEDIFF (MI,INTIME5,OUTTIME5),0) +  ISNULL(DATEDIFF (MI,INTIME6,OUTTIME6),0) +  " +
           "\n" + "ISNULL(DATEDIFF (MI,INTIME7,OUTTIME7),0) +  ISNULL(DATEDIFF (MI,INTIME8,OUTTIME8),0) AS WORKEDMINUTES, " +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.INTIME1)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.INTIME1)),2)) AS IN1 , " +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.INTIME2)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.INTIME2)),2)) AS IN2  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.INTIME3)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.INTIME3)),2)) AS IN3  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.INTIME4)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.INTIME4)),2)) AS IN4  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.INTIME5)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.INTIME5)),2)) AS IN5  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.INTIME6)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.INTIME6)),2)) AS IN6  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.INTIME7)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.INTIME7)),2)) AS IN7  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.INTIME8)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.INTIME8)),2)) AS IN8  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.OUTTIME1)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.OUTTIME1)),2)) AS OUT1  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.OUTTIME2)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.OUTTIME2)),2)) AS OUT2  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.OUTTIME3)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.OUTTIME3)),2)) AS OUT3  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.OUTTIME4)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.OUTTIME4)),2)) AS OUT4  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.OUTTIME5)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.OUTTIME5)),2)) AS OUT5  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.OUTTIME6)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.OUTTIME6)),2)) AS OUT6  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.OUTTIME7)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.OUTTIME7)),2)) AS OUT7  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,AT.OUTTIME8)),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,AT.OUTTIME8)),2)) AS OUT8  ," +
           "\n" + "CONVERT(FLOAT, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(HH,ISNULL(AT.OUTTIME8,ISNULL(AT.OUTTIME7,ISNULL(AT.OUTTIME6,ISNULL(AT.OUTTIME5,ISNULL(AT.OUTTIME4,ISNULL(AT.OUTTIME3, ISNULL(AT.OUTTIME2,AT.OUTTIME1))))))) )),2) + '.' + RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR, DATEPART(MI,ISNULL(AT.OUTTIME8,ISNULL(AT.OUTTIME7,ISNULL(AT.OUTTIME6,ISNULL(AT.OUTTIME5, ISNULL(AT.OUTTIME4,ISNULL(AT.OUTTIME3,ISNULL(AT.OUTTIME2,AT.OUTTIME1))))))) )),2)) AS LASTOUT," +
           "\n" + " RIGHT(REPLICATE('0',2) +  CONVERT(VARCHAR, DATEPART(HH,AT.INTIME1)),2) + ':'  + RIGHT(REPLICATE('0',2) +  CONVERT(VARCHAR, DATEPART(MI,AT.INTIME1)),2) AS FIRSTIN, " +
           "\n" + "AT.INTIME1,AT.INTIME2,AT.INTIME3,AT.INTIME4,AT.INTIME5, AT.INTIME6,AT.INTIME7,AT.INTIME8,  AT.OUTTIME1,AT.OUTTIME2,AT.OUTTIME3,AT.OUTTIME4,AT.OUTTIME5,AT.OUTTIME6,AT.OUTTIME7, AT.OUTTIME8 ,  DM.DEPARTMENTNAME," +
           "\n" + " PSH.SHIFTNAME + '  ['+ RIGHT(REPLICATE('0',2) +  CONVERT(VARCHAR, DATEPART(HH,PSH.BEGINTIME)),2) + ':'+ RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,DATEPART(MI,PSH.BEGINTIME)),2) + '-'" +
           "\n" + " + RIGHT(REPLICATE('0',2)+ CONVERT(VARCHAR,DATEPART(HH,PSH.ENDTIME)),2) + ':'+ RIGHT(REPLICATE('0',2)+ CONVERT(VARCHAR,DATEPART(MI,PSH.ENDTIME)),2) + ']' " +
           "\n" + "  AS SHIFTNAME,AT.INACTIVE AS INACTIVE,ISNULL(TM.TEAMNAME,'') + ' ' + ISNULL(TM.REMARKS,'')  AS TEAMNAME," +
           "\n" + " CM.CATEGORYNAME,GM.GRADENAME,DM.DEPARTMENTID,CM.CATEGORYID,GM.GRADEID,DIM.DESIGNATIONID,DIM.DESIGNATIONNAME ,    " +
           "\n" + " (CONVERT(INT,DATEPART(HH,INTIME1)) * 60 + CONVERT(INT,DATEPART(MI,INTIME1))  - " +
           "\n" + " (CONVERT(INT,DATEPART(HH,PSH.BEGINTIME)) * 60 + CONVERT(INT,DATEPART(MI,PSH.BEGINTIME))))  AS LATECOMINGMINUTES," +
           "\n" + " CONVERT(INT,DATEPART(HH,ISNULL(AT.OUTTIME8,ISNULL(AT.OUTTIME7,ISNULL(AT.OUTTIME6,ISNULL(AT.OUTTIME5, ISNULL(AT.OUTTIME4,ISNULL(AT.OUTTIME3,ISNULL(AT.OUTTIME2,AT.OUTTIME1))))))))) * 60 + CONVERT(INT,DATEPART(MI,ISNULL(AT.OUTTIME8,ISNULL(AT.OUTTIME7,ISNULL(AT.OUTTIME6,ISNULL(AT.OUTTIME5, ISNULL(AT.OUTTIME4,ISNULL(AT.OUTTIME3,ISNULL(AT.OUTTIME2,AT.OUTTIME1)))))))))  - " +
           "\n" + "  (CONVERT(INT,DATEPART(HH,PSH.ENDTIME)) * 60 + CONVERT(INT,DATEPART(MI,PSH.ENDTIME))) AS EARLYGOINGMINUTES ," +
           "\n" + " (SELECT  MAX(ATTENDANCEDATE) FROM TK_ATTENDANCE WHERE (STATUS = 'P' OR STATUS = 'PX') " +
           "\n" + "  AND EMPLOYEEID = EM.EMPLOYEEID ) AS LASTPRESENTDATE,AT.WEEKLYOFF,AT.HOLIDAY,SGM.SHIFTGROUPNAME, SH.SHIFTNAME AS ALLOTEDSHIFT, PSH.SHIFTNAME AS PRESENTSHIFT, OVERTIME, AT.HALFDAY, AT.HALFDAYLEAVE,LM.LOCATIONNAME,SEM.SECTIONNAME, REM.EMPLOYEEFIRSTNAME + ' ' + REM.EMPLOYEELASTNAME AS REPORTLEVEL1,EM.REPORTINGEMPLOYEEID1, " +
           "\n" + " IN1READERID,IN2READERID,IN3READERID,IN4READERID,IN5READERID,IN6READERID,IN7READERID,IN8READERID, " +
           "\n" + " OUT1READERID,OUT2READERID,OUT3READERID,OUT4READERID,OUT5READERID,OUT6READERID,OUT7READERID,OUT8READERID, AT.LATECOMINGEXCLUDE,AT.EARLYGOINGEXCLUDE " +
           "\n" + "FROM TK_ATTENDANCE AT   " +
           "\n" + "INNER JOIN TK_EMPLOYEE EM ON EM.EMPLOYEEID = AT.EMPLOYEEID   " +
           "\n" + "INNER JOIN TK_LATEPOLICY LP ON LP.LATEPOLICYID = EM.LATEPOLICYID " +
           "\n" + "INNER JOIN TK_SHIFT SH ON SH.SHIFTID = AT.ALLOTEDSHIFTID    " +
           "\n" + "INNER JOIN TK_SHIFT PSH ON PSH.SHIFTID = AT.PRESENTSHIFTID   " +
           "\n" + " INNER JOIN TK_SECTION SEM ON SEM.SECTIONID = EM.SECTIONID " +
           "\n" + " INNER JOIN TK_DEPARTMENT DM ON DM.DEPARTMENTID = SEM.DEPARTMENTID " +
           "\n" + " INNER JOIN TK_CATEGORY CM ON CM.CATEGORYID = EM.CATEGORYID " +
           "\n" + "INNER JOIN TK_SHIFTGROUP SGM ON SGM.SHIFTGROUPID = EM.SHIFTGROUPID " +
           "\n" + " INNER JOIN TK_GRADE GM ON GM.GRADEID = EM.GRADEID " +
           "\n" + " INNER JOIN TK_DESIGNATION DIM ON DIM.DESIGNATIONID = EM.DESIGNATIONID " +
           "\n" + " LEFT JOIN TK_TEAM TM ON TM.TEAMID = EM.TEAMID " +
          "\n" + " LEFT JOIN TK_EMPLOYEE REM ON EM.REPORTINGEMPLOYEEID1 = REM.EMPLOYEEID " +
           "\n" + " INNER JOIN TK_LOCATION LM ON LM.LOCATIONID = EM.LOCATIONID ";


        return SubQueryStr;
    }


    public string GetStr(Boolean WHBasedFILO, Int64 CompanyID)
    {
        //LoadSelections();

        string str = "SELECT EMPLOYEEID, EMPLOYEECODE, EMPLOYEENAME, STATUS, GENDER, SHIFTID, BEGINTIME, ENDTIME, SHIFTDURATION, SHIFTDURATIONMINUTES, " +
              " WORKEDHOURS, EXTRALESSWORKMINUTES, WORKEDMINUTES,SECTIONID " +
              " IN1, IN2, IN3, IN4, IN5, IN6, IN7, IN8, OUT1, OUT2, OUT3, OUT4, OUT5, OUT6, OUT7, OUT8,FIRSTIN, LASTOUT,LATECOMINGEXCLUDE,EARLYGOINGEXCLUDE, " +
              " INTIME1, INTIME2, INTIME3, INTIME4, INTIME5, INTIME6, INTIME7, INTIME8, OUTTIME1, OUTTIME2, OUTTIME3, OUTTIME4, OUTTIME5, OUTTIME6, OUTTIME7, OUTTIME8, " +
              " DEPARTMENTNAME, SHIFTNAME, INACTIVE, TEAMNAME, CATEGORYNAME, GRADENAME, DEPARTMENTID, CATEGORYID, GRADEID, DESIGNATIONID, DESIGNATIONNAME,SECTIONNAME, " +
              " CASE WHEN ((LATECOMINGMINUTES > DATEPART(mi, LATECOMINGGRACETIME)) OR (LATECOMINGMINUTES < 0)) " +
              " THEN LATECOMINGMINUTES " +
              " ELSE 0 END LATECOMINGMINUTES, " +
              " CASE WHEN ((EARLYGOINGMINUTES < -DATEPART(mi, EARLYGOINGGRACETIME)) OR (EARLYGOINGMINUTES > 0)) " +
              " THEN EARLYGOINGMINUTES " +
              " ELSE 0 END EARLYGOINGMINUTES, CONVERT(VARCHAR,LASTPRESENTDATE,105) AS LASTPRESENTON,  LASTPRESENTDATE,WEEKLYOFF,  SHIFTGROUPNAME,  " +
              " ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,(EXTRALESSWORKMINUTES/60)) +  '.'  + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2)  + CONVERT(VARCHAR,ABS(EXTRALESSWORKMINUTES) - ( ABS((EXTRALESSWORKMINUTES/60)*60))),2))),0) AS EXTRALESSWORKHOURS, " +
             "\n" + "CASE WHEN ((LATECOMINGMINUTES > DATEPART(mi, LATECOMINGGRACETIME)) OR (LATECOMINGMINUTES < 0)) THEN ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,FLOOR(LATECOMINGMINUTES/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(LATECOMINGMINUTES) - (ABS(LATECOMINGMINUTES)/60)*60),2))),0) ELSE 0 END AS LATECOMINGHOURS ," +
            "\n" + " CASE WHEN ((EARLYGOINGMINUTES < -DATEPART(mi, EARLYGOINGGRACETIME)) OR (EARLYGOINGMINUTES > 0)) THEN ISNULL(CONVERT(FLOAT,CONVERT(VARCHAR,FLOOR(EARLYGOINGMINUTES/60)) +  '.' + CONVERT(VARCHAR, RIGHT(REPLICATE('0',2) + CONVERT(VARCHAR,ABS(EARLYGOINGMINUTES) - (ABS(EARLYGOINGMINUTES)/60)*60),2))),0) ELSE 0 END AS EARLYGOINGHOURS, ALLOTEDSHIFT, PRESENTSHIFT, ISONLEAVE, ISONTOUR, HOLIDAY, OVERTIME, HALFDAY, HALFDAYLEAVE, ATTENDANCEDATE, " +
                     "\n" + " IN1READERID,IN2READERID,IN3READERID,IN4READERID,IN5READERID,IN6READERID,IN7READERID,IN8READERID, " +
       "\n" + " OUT1READERID,OUT2READERID,OUT3READERID,OUT4READERID,OUT5READERID,OUT6READERID,OUT7READERID,OUT8READERID, " +
       "\n" + " '' AS IN1LOCATION, '' AS IN2LOCATION , '' AS IN3LOCATION, '' AS IN4LOCATION , '' AS IN5LOCATION, '' AS IN6LOCATION, '' AS IN7LOCATION, '' AS IN8LOCATION, " +
        "\n" + " '' AS OUT1LOCATION, '' AS OUT2LOCATION , '' AS OUT3LOCATION, '' AS OUT4LOCATION , '' AS OUT5LOCATION, '' AS OUT6LOCATION, '' AS OUT7LOCATION, '' AS OUT8LOCATION " +
            "\n" + " FROM (" + RawQueryForAll(WHBasedFILO ) + " WHERE EM.COMPANYID = " + CompanyID + " ) A";

        return str;
    }


}
